
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import ClientProvider from "@/components/ClientProvider";
import { SideBar } from "@/components/SideBar";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <ClientProvider>
      <body suppressHydrationWarning={true}
        className={`transition-all duration-300 dark:bg-Dbackground  bg-background font-winky text-text dark:text-Dtext`}
        >
{/* desktop */}
          <main className="mdsm:flex hidden w-full">
        <SideBar/>
        <div className="min-w-[50%] w-screen ">
        <Header/>
        {children}
        </div>
          </main>



          {/* mobile */}
          <main className="mdsm:hidden py-0">
          <Header/>
          <SideBar/>
          
        {children}
          </main>

      </body>
        </ClientProvider>
    </html>
  );
}
